[package]
name = "polkadot-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
log = { version = "0.3", optional = true }
serde = { version = "1.0", default_features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default_features = false}
polkadot-primitives = { path = "../primitives", default_features = false }
substrate-codec = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-serializer = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-std = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-io = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-support = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-primitives = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-keyring = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-consensus = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-council = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-democracy = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-executive = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-primitives = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-session = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-staking = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-system = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-timestamp = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-version = { git = "https://github.com/paritytech/paritysubstrate" }

[dev-dependencies]
hex-literal = "0.1.0"

[features]
default = ["std"]
std = [
	"polkadot-primitives/std",
	"substrate-codec/std",
	"substrate-primitives/std",
	"substrate-runtime-std/std",
	"substrate-runtime-io/std",
	"substrate-runtime-support/std",
	"substrate-runtime-consensus/std",
	"substrate-runtime-council/std",
	"substrate-runtime-democracy/std",
	"substrate-runtime-executive/std",
	"substrate-runtime-primitives/std",
	"substrate-runtime-session/std",
	"substrate-runtime-staking/std",
	"substrate-runtime-system/std",
	"substrate-runtime-timestamp/std",
	"substrate-runtime-version/std",
	"serde_derive",
	"serde/std",
	"log",
	"safe-mix/std"
]
