[package]
name = "adder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"

[dependencies]
polkadot-parachain = { path = "../../parachain/", default-features = false }
substrate-codec-derive = { git = "https://github.com/paritytech/polkadot", branch = "split-substrate", default-features = false }
tiny-keccak = "1.4"
