[package]
name = "polkadot-statement-table"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
substrate-codec = { git = "https://github.com/paritytech/polkadot", branch = "split-substrate" }
substrate-codec-derive = { git = "https://github.com/paritytech/polkadot", branch = "split-substrate" }
substrate-primitives = { git = "https://github.com/paritytech/polkadot", branch = "split-substrate" }
polkadot-primitives = { path = "../primitives" }
