[package]
name = "adder-wasm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
adder = { path = ".." }
polkadot-parachain = { path = "../../../parachain", default-features = false, features = ["wasm-api"] }
tiny-keccak = "1.4"
dlmalloc = { version = "0.1.2", features = ["global"] }

[lib]
crate-type = ["cdylib"]

[target.release]
panic = "abort"
lto = true

[workspace]
