[package]
name = "polkadot-consensus"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1.17"
parking_lot = "0.4"
tokio = "0.1.7"
ed25519 = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
error-chain = "0.12"
log = "0.3"
exit-future = "0.1"
rhododendron = "0.3"
polkadot-api = { path = "../api" }
polkadot-availability-store = { path = "../availability-store" }
polkadot-parachain = { path = "../parachain" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-statement-table = { path = "../statement-table" }
polkadot-transaction-pool = { path = "../transaction-pool" }
substrate-bft = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
substrate-codec = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
substrate-runtime-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
substrate-client = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
substrate-runtime-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }

[dev-dependencies]
substrate-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot" }
