[package]
name = "polkadot-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.12"
polkadot-executor = { path = "../executor" }
polkadot-runtime = { path = "../runtime" }
polkadot-primitives = { path = "../primitives" }
substrate-codec = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-io = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-runtime-executive = { path  = "../../substrate/runtime/executive" }
substrate-runtime-primitives = { path  = "../../substrate/runtime/primitives" }
substrate-client = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-primitives = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-executor = { git = "https://github.com/paritytech/paritysubstrate" }
substrate-state-machine = { git = "https://github.com/paritytech/paritysubstrate" }

[dev-dependencies]
substrate-keyring = { git = "https://github.com/paritytech/paritysubstrate" }
